export const GAMES_MAX_PAGE_SIZE = 10;
export const SUMMONERS_RIFT_HEIGHT = 15000;
export const SUMMONERS_RIFT_WIDTH = 15000;
export const MAX_MATCH_HISTORY_GAMES = 100;
export const DRAWER_WIDTH = 230;